site_name: "{{ cookiecutter.project_name }}"

theme:
  name: "material"

markdown_extensions:
  # Footnotes
  - footnotes
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg 
  # Checkboxes
  - pymdownx.tasklist:
      custom_checkbox: true
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Mermaid diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  # Navigation page ordering
  - awesome-pages
  - search

copyright: |
  Copyrighted to the {{ cookiecutter.group_name }} team members at KAMK in {{ cookiecutter.__year_nro }}.
