site_name: '{{ cookiecutter.project_name }}'

theme:
  name: 'material'

markdown_extensions:
  # Footnotes
  - footnotes
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Checkboxes
  - pymdownx.tasklist:
      custom_checkbox: true
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences


plugins:
  # Navigation page ordering
  - awesome-pages
  - search
  # PlantUML support using the Docker container
  - plantuml:
      puml_url: "http://{{ cookiecutter.project_slug }}-puml:8080"
      num_workers: 4

copyright: |
  Copyrighted to the {{ cookiecutter.group_name }} team members at Kajaani University of Applied Sciences in {{ cookiecutter.__year_nro }}. 
  KAMK and the customer company (if any) have the right to use the material for their own purposes.
