services:
  project-cookie-serve:
    build:
      context: .
      dockerfile: developmental/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TEMPLATE_NAME=project
    command: ["project"]
  puml:
    image: plantuml/plantuml-server:latest
