services:
  oat-cookie-serve:
    build:
      context: .
      dockerfile: developmental/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TEMPLATE_NAME=oppimispaivakirja
    command: ["oppimispaivakirja"]
