name: {{ cookiecutter.course_slug ~ ' - ' ~ cookiecutter.__uniqueness_id ~ ' - mkdocs' }}

services:
  mkdocs:
    container_name: {{ cookiecutter.__uniqueness_id ~ '-container' }}
    build:
      context: .
      dockerfile: docs.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
    working_dir: /docs
    command: ["uv", "run", "mkdocs", "serve", "--dev-addr=0.0.0.0:8000", "--watch=docs"]
