version: '3'

name: {{ cookiecutter.course_slug }}-{{cookiecutter.__uniqueness_id}}-mkdocs

services:
  mkdocs:
    container_name: {{ cookiecutter.__uniqueness_id }}-container
    image: kamk/{{ cookiecutter.__uniqueness_id }}-diary:latest
    build:
      context: .
      dockerfile: docs.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
    working_dir: /docs
    command: ["serve", "--dev-addr=0.0.0.0:8000", "--watch=docs"]