version: '3'

services:
  {{ cookiecutter.course_slug }}-mkdocs:
    container_name: {{ cookiecutter.course_slug }}-mkdocs
    image: kamk/{{ cookiecutter.course_slug }}-diary:latest
    build:
      context: .
      dockerfile: docs.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
    working_dir: /docs
    command: ["serve", "--dev-addr=0.0.0.0:8000", "--watch=docs"]