name: "{{cookiecutter.__course_slug + '-' + cookiecutter.__uniqueness_id}}"

services:
  mkdocs:
    container_name: "{{cookiecutter.__uniqueness_id}}-mkdocs"
    image: kamk/{{cookiecutter.__uniqueness_id}}-report:latest
    build:
      context: .
      dockerfile: docs.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
    working_dir: /docs
    command: ["serve", "--dev-addr=0.0.0.0:8000", "--watch=docs"]
    depends_on:
      - puml
    networks:
      - {{ cookiecutter.__uniqueness_id }}_network
  puml:
    container_name: "{{ cookiecutter.__uniqueness_id }}-puml"
    image: plantuml/plantuml-server:latest
    networks:
      - {{ cookiecutter.__uniqueness_id }}_network

networks:
    {{ cookiecutter.__uniqueness_id }}_network:
        name: {{ cookiecutter.__uniqueness_id }}_network
