version: '3'

services:
  {{ cookiecutter.project_slug }}-mkdocs:
    container_name: "{{ cookiecutter.project_slug }}-mkdocs"
    image: kamk/{{ cookiecutter.project_slug }}-report:latest
    build:
      context: .
      dockerfile: docs.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
    working_dir: /docs
    command: ["serve", "--dev-addr=0.0.0.0:8000", "--watch=docs"]
    networks:
      - {{ cookiecutter.project_slug }}_network

networks:
    {{ cookiecutter.project_slug }}_network:
        name: {{ cookiecutter.project_slug }}_network
